// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiQp4Bamtmi7FADS-bFbZZoPPqC4-2GEM',
    appId: '1:892021988060:web:your_web_app_id',
    messagingSenderId: '892021988060',
    projectId: 'stayfresh-36edf',
    authDomain: 'stayfresh-36edf.firebaseapp.com',
    storageBucket: 'stayfresh-36edf.firebasestorage.app',
    measurementId: 'G-MEASUREMENT_ID',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiQp4Bamtmi7FADS-bFbZZoPPqC4-2GEM',
    appId: '1:892021988060:android:1d14c491862826971f7219',
    messagingSenderId: '892021988060',
    projectId: 'stayfresh-36edf',
    storageBucket: 'stayfresh-36edf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: '1:892021988060:ios:your_ios_app_id',
    messagingSenderId: '892021988060',
    projectId: 'stayfresh-36edf',
    storageBucket: 'stayfresh-36edf.firebasestorage.app',
    iosBundleId: 'com.example.stayfresh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: '1:892021988060:macos:your_macos_app_id',
    messagingSenderId: '892021988060',
    projectId: 'stayfresh-36edf',
    storageBucket: 'stayfresh-36edf.firebasestorage.app',
    iosBundleId: 'com.example.stayfresh',
  );
}